### ISSUE TITLE
Fail to train with Lora

### ISSUE THREAD

**Issue by jzzzf** [AIoT-MLSys-Lab/SVD-LLM#19]
Hello， I am trying to reproduce your method using Llama2 with LoRA, but I have encountered two issues. First, the loss drops to zero after just a few steps. Second, when I attempt to test the trained model, I encounter an error：
```python
Traceback (most recent call last):
  File "/data2/gaoxx/SVD-LLM-main/SVDLLM-copy.py", line 791, in <module>
    ppl_eval(model, tokenizer, datasets=['wikitext2'], model_seq_len=args.model_seq_len, batch_size=args.eval_batch_size, device=args.DEV)
  File "/data2/gaoxx/anaconda3/envs/svd_gxx1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data2/gaoxx/SVD-LLM-main/evaluater.py", line 33, in ppl_eval
    ppl = np.exp(torch.cat(nlls, dim=-1).mean().item())
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

Can you provide more detail about training the compressed model with lora?

**Comment by jzzzf** [comment]
I have resolved this issue. When performing LoRA fine-tuning on the Lllama2-7B model, set `bf16=True` instead of `fp16=True`.
